server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: wisdom
    password: byx4531925000

eureka:
  client:
    register-with-eureka: true #表示将自己注册进eurekaserver默认为true
    fetch-registry: true #是否从eurekaserver抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true #访问路径可以显示ip地址
    lease-renewal-interval-in-seconds: 1 #eureka客户端向服务端发送心跳的时间间隔，默认为30s
    lease-expiration-duration-in-seconds: 2 #eureka服务端在收到最后一次心跳后等待的时间上限，默认为90s，超时将剔除

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.wisdom.springcloud.entities